### ISSUE TITLE
fields::circulantEmbeddingSetup question

### ISSUE THREAD

**Issue by DanWismer** [dnychka/fieldsRPackage#6]
Hi,

I am getting this error `if (any(d < 0)) stop("distance argument must be nonnegative"): missing value where TRUE/FALSE needed` when running the follow function:

```
  # create object for simulation
  obj <- fields::circulantEmbeddingSetup(
    grid = list(
      x = seq(0, 5, length.out = terra::nrow(x)),
      y = seq(0, 5, length.out = terra::ncol(x))
    ),
    Covariance = "Exponential",
    aRange = scale
  )
  ```
  
  I am unsure how to debug this one. Wondering if you had any suggestions? 
  
  Thanks!

**Comment by dnychka** [comment]
Your call looks OK.
Did you check  the nrow(x) and ncol(x) ?


Douglas Nychka
Personal email
Cell 3037253199

From: Dan Wismer ***@***.***>
Date: Friday, August 23, 2024 at 10:46 AM
To: dnychka/fieldsRPackage ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dnychka/fieldsRPackage] fields::circulantEmbeddingSetup question (Issue #6)

Hi,

I am getting this error if (any(d < 0)) stop("distance argument must be nonnegative"): missing value where TRUE/FALSE needed when running the follow function:

  # create object for simulation

  obj <- fields::circulantEmbeddingSetup(

    grid = list(

      x = seq(0, 5, length.out = terra::nrow(x)),

      y = seq(0, 5, length.out = terra::ncol(x))

    ),

    Covariance = "Exponential",

    aRange = scale

  )

I am unsure how to debug this one. Wondering if you had any suggestions?

Thanks!

**Comment by DanWismer** [comment]
Thanks,

terra::nrow(x) = 1 AND terra::ncol(x) = 2

**Comment by dnychka** [comment]
This function is designed for large problems  e.g. grids of 100X100 and larger.
I did not write it to handle a grid of just on point which is what nrow  is.

You should just use the simpler function  sim.spatialProcess.


Douglas Nychka
Personal email
Cell 3037253199

From: Dan Wismer ***@***.***>
Date: Monday, August 26, 2024 at 10:53 AM
To: dnychka/fieldsRPackage ***@***.***>
Cc: Douglas Nychka ***@***.***>, Comment ***@***.***>
Subject: Re: [dnychka/fieldsRPackage] fields::circulantEmbeddingSetup question (Issue #6)

Thanks,

terra::nrow(x) = 1 AND terra::ncol(x) = 2

**Comment by DanWismer** [comment]
Thanks for your responses dynchka, my data going into the function was the problem as you mentioned. Cheers.
